### ISSUE TITLE
Upload a version to pypi

### ISSUE THREAD

**Issue by alexntt** [DjangoAdminHackers/django-admin-row-actions#4]
Hi,

Could you upload a version to pypi? We are using this and it's working beautifully, but it's a chore to install from Git.

Kind regards,

Álex

**Comment by andybak** [comment]
I'd love to put it on PyPi. It's lacking tests which makes me a bit ashamed, the docs are out of date and the API has been in flux. However it could definitely be a 0.1 or 0.5 release.

Would you be interested in being added as a maintainer? I'm fairly rusty with PyPi and setup.py matters and it will happen a lot quicker if someone else would help. ;-)

**Comment by alexntt** [comment]
I don't have much pypi experience either, just uploading packages to work's internal pypi server. setup.py looks good enough for an upload. The project is good enough for our purposes right now, so I'd be happy with an upload as-is; however I can try to help if that's going to be useful, let me know what you need.

**Comment by blag** [comment]
I'm happy to be added as a maintainer for both/either GitHub and PyPI. 😄 

I think it would be good to have #8 merged in before a new version is released to PyPI though.

**Comment by andybak** [comment]
Hi @blag - you're added as a collaborator here. Send me your email address and we'll chat about PyPi

**Comment by blag** [comment]
@alexntt Version 0.0.1 is now on PyPI, you can install it with pip:

``` bash
pip install django-admin-row-actions
```

This project doesn't yet have any tests, so just be mindful of that before using it in production. Also, on that note, PRs that add tests would be gratefully accepted.

Since #9 is just updating the documentation, and the release to PyPI exists, I'm going to close this issue. That PR should be merged soon once it gets a quick review.
